version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - shared_uploads:/shared/uploads
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=UTC
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - N8N_CREDENTIALS_OVERWRITE={"OpenAi Api":{"apiKey":"${OPENAI_API_KEY}"}}

    volumes:
      - n8n_data:/home/node/.n8n
      - shared_uploads:/shared/uploads

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

volumes:
  n8n_data:
  postgres_data:
  shared_uploads:
